### ISSUE TITLE
Fails to install on python 3.7 or later

### ISSUE THREAD

**Issue by schloegl** [ManchesterBioinference/GP_Transcription_Dynamics#1]
I'm trying to install this GP_Transcription_Dynamics package, but fail to run 
   pip install -r requirements.txt
w/o error. 

The requirements are very restricting. I've tried countless approaches to relax the requirements, but failed to get a successful installation. I've tried several python versions including 3.6, 3.7, 3.9, 3.10, 3.11. 

Python 3.6 is broken because any recent version of pip fails to run. 
Python 3.7 and later does not support dataclasses==0.7.0, Cython==0.29.21 need to be relaxed, and that goes on for tensorflow, numpy, pandas, ipython, ipykernel, google-colab, tornado, six, etc. Unfortunately, none of these attempts were successful. 

Can you provide a solution for running GP_Transcription_Dynamics on python 3.9 or later ?

**Comment by schloegl** [comment]
Finally, I managed to get it installed in python 3.9. I had to remove sk-learn and all version restrictions from the requirements.txt file, in order to make it work. I did not test correct behaviour, because I do not know how to test correctness.

**Comment by YuliyaShapovalova** [comment]
Thanks for reaching out. The released code was indeed run on Python 3.6. We are now working on a new release for Python 3.8/3.9. It should be available in a couple of weeks.
