### ISSUE TITLE
load_filtered_data module does not exist in repo

### ISSUE THREAD

**Issue by jakeyeung** [ManchesterBioinference/GP_Transcription_Dynamics#2]
Hello GP team,

In the `simulated_examples.py`, it wants to import `load_filtered_data` module from `utils.utilities`.

However, `load_filtered_data` does not exist in any of the code in the repository. 

Could you maybe provide this `load_filtered_data` function into the repo?

Jake

**Comment by YuliyaShapovalova** [comment]
Thanks for your interest, Jake! My bad — you don’t need to load this function at all. I've updated the file.

**Comment by jakeyeung** [comment]
Thanks for the quick reply.

This `load_filtered_data` function occurs in 4 other places in the experiments folder. 

Can you confirm that you do not need to load this function either in the experiments folder? Otherwise one would need to include it in `utils.utilities`.



https://github.com/ManchesterBioinference/GP_Transcription_Dynamics/search?q=load_filtered_data

Jake

**Comment by YuliyaShapovalova** [comment]
Yes, I confirm that this function is not needed anywhere. Please, see the updated repository.
